In [9]:
import pandas as pd
data = pd.read_csv("./archive/melb_data.csv")

In [10]:
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [13]:
for x in range(1,51):
    if x % 3 == 0 and x % 5 == 0 :
        print("multiplo de 3 y 5!")
    elif x % 3 == 0:
        print("multiplo de 3!")
    elif x % 5 == 0:
        print ("multiplo de 5!")
    else: 
        print(x)

1
2
multiplo de 3!
4
multiplo de 5!
multiplo de 3!
7
8
multiplo de 3!
multiplo de 5!
11
multiplo de 3!
13
14
multiplo de 3 y 5!
16
17
multiplo de 3!
19
multiplo de 5!
multiplo de 3!
22
23
multiplo de 3!
multiplo de 5!
26
multiplo de 3!
28
29
multiplo de 3 y 5!
31
32
multiplo de 3!
34
multiplo de 5!
multiplo de 3!
37
38
multiplo de 3!
multiplo de 5!
41
multiplo de 3!
43
44
multiplo de 3 y 5!
46
47
multiplo de 3!
49
multiplo de 5!

In [6]:
def fib(nterms):
    a, b = 0, 1
    for i in range(nterms):
        print(a)
        a, b = b, a+b
    
fib(10)

0
1
1
2
3
5
8
13
21
34

In [12]:
def rec_fib(n):
    if n <= 1:
        return n
    else:
        return rec_fib(n-1)+rec_fib(n-2)

for i in range(10):
    print(rec_fib(i))

0
1
1
2
3
5
8
13
21
34